#! /usr/bin/python
# fever
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 4; coding: utf-8 -*-
#
# Copyright © 2013-2014 Gwendal Le Bihan
# 
# This file is part of Fever.
# 
# Fever is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Fever is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Fever.  If not, see <http://www.gnu.org/licenses/>.

from Fever.main import Application
import optparse
import gettext
import logging

gettext.install("fever", "/usr/share/locale")

if __name__ == "__main__":
    optparser = optparse.OptionParser()
    optparser.add_option('--share-dir', dest = "share_dir", default = "/usr/share", help = _("Set share folder path"))
    optparser.add_option('-d', '--debug-level', dest = "debug_level", default = 1, help = _("Set debug level"), type = int)
    options, args = optparser.parse_args()
    
    if options.debug_level > 4:
        options.debug_level = 4
    if options.debug_level < 0:
        options.debug_level = 0
    
    if options.debug_level == 4:
        logging.getLogger().setLevel(logging.DEBUG)
    elif options.debug_level == 3:
        logging.getLogger().setLevel(logging.INFO)
    elif options.debug_level == 2:
        logging.getLogger().setLevel(logging.WARNING)
    elif options.debug_level == 1:
        logging.getLogger().setLevel(logging.ERROR)
    elif options.debug_level == 0:
        logging.getLogger().setLevel(logging.CRITICAL)
    
    Application(options).run()
